### Post request routes

### Get post list
GET http://localhost:3000/posts

### Get post by id
GET http://localhost:3000/posts/4

### Create post
POST http://localhost:3000/posts
Content-Type: application/json

{
 "title": "New Post",
 "content": "This is the content of the new post."
}

### Update post
PUT http://localhost:3000/posts/5
Content-Type: application/json

{
 "title": "Updated Post",
 "content": "This is the updated content of the post."
}

### Delete post
DELETE http://localhost:3000/posts/5
