#User Module Requests

### Get User List
GET http://localhost:3000/users?email=sddsf

### Create User
POST http://localhost:3000/users
content-type: application/json

{
  "name": "John Doe",
  "email": "john.doe1@example.com",
  "phoneNumber": "+911234567890",
  "password": "securepassword"
}

### Get User
GET http://localhost:3000/users/5

### Update User
PUT http://localhost:3000/users/5
content-type: application/json

{
  "name": "John Doe 2",
  "email": "john.doe@example.com",
  "phoneNumber": "+911234567891"
}

### Delete User
DELETE http://localhost:3000/users/2